language: php

sudo: false

cache:
    directories:
        - $HOME/.composer/cache
        - $HOME/phpcs-cache

php:
  - 7.1
  - 7.2
  - 7.3

env:
  - RUN_TESTS=1

matrix:
  fast_finish: true
  include:
    - php: 7.3
      env: COMPOSER_EXTRA_ARGS="--prefer-stable" COVERAGE="--coverage ./coverage.xml --coverage-src ./src" TESTER_RUNTIME="phpdbg"
    - php: 7.3
      env: COMPOSER_EXTRA_ARGS="--prefer-stable" PHPSTAN=1 RUN_TESTS=0
    - php: 7.3
      env: COMPOSER_EXTRA_ARGS="--prefer-stable" CODING_STANDARD=1 RUN_TESTS=0
  exclude:
    - php: 7.3
      env: COMPOSER_EXTRA_ARGS="--prefer-stable"

before_install:
  - travis_retry composer self-update

install:
  - travis_retry composer update --no-interaction --no-suggest --no-progress --prefer-dist $COMPOSER_EXTRA_ARGS
  - if [ "$COVERAGE" != "" ]; then travis_retry wget -O /tmp/coveralls.phar https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar; fi

script:
  - if [ "$PHPSTAN" = "1" ]; then vendor/bin/phpstan analyse --level=7 -c phpstan.neon src tests/KdybyTests; fi
  - if [ "$CODING_STANDARD" = "1" ]; then php vendor/bin/phpcs --standard=ruleset.xml --cache=$HOME/phpcs-cache/.phpcs-cache --encoding=utf-8 -sp src tests; fi
  - if [ "$CODING_STANDARD" = "1" ]; then vendor/bin/parallel-lint -e php,phpt --exclude vendor .; fi
  - if [ "$RUN_TESTS" = "1" ]; then vendor/bin/tester $COVERAGE -s -p ${TESTER_RUNTIME:-php} -c ./tests/php.ini-unix ./tests/KdybyTests/; fi

after_script:
  - if [ "$COVERAGE" != "" ]; then vendor/bin/php-coveralls --verbose --config tests/.coveralls.yml || true; fi

after_failure:
  - 'for i in $(find ./tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done'
